name: people_counter_analytics
description: "A beautiful, cross-platform dashboard for analyzing people counter data."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Default iOS-style icons
  cupertino_icons: ^1.0.8

  # --- OUR CUSTOM PACKAGES ---
  # Used for drawing the beautiful data charts
  fl_chart: ^0.65.0
  # Used for selecting the .scb data folder on Windows/Android
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  pdf: ^3.11.0
  printing: ^5.11.1
  ftp_server: ^2.1.1
  minio: ^3.5.8
  path: ^1.9.1
  webview_flutter: ^4.7.0
  url_launcher: ^6.2.5
  webview_windows: ^0.3.0
  excel: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Ensures that the Material Design icons are included
  uses-material-design: true
  generate: true
  assets:
    - assets/boitex_logo.png



