// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt4cnbgPE92j9ilB8vmZqfbqz7DA4ucTA',
    appId: '1:1075074014920:web:24984c45459561fd058ffd',
    messagingSenderId: '1075074014920',
    projectId: 'boitexinfo-analytics-fab54',
    authDomain: 'boitexinfo-analytics-fab54.firebaseapp.com',
    storageBucket: 'boitexinfo-analytics-fab54.firebasestorage.app',
    measurementId: 'G-8JSWLFYRPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB23QHMYYt7C29r8eQGMIr7Vkmlj32LJI',
    appId: '1:1075074014920:android:b96f17081603b36e058ffd',
    messagingSenderId: '1075074014920',
    projectId: 'boitexinfo-analytics-fab54',
    storageBucket: 'boitexinfo-analytics-fab54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZuHU-GxiWgJ5gsDkEkOAb7od3QhCNXzg',
    appId: '1:1075074014920:ios:80306f8250377445058ffd',
    messagingSenderId: '1075074014920',
    projectId: 'boitexinfo-analytics-fab54',
    storageBucket: 'boitexinfo-analytics-fab54.firebasestorage.app',
    iosBundleId: 'com.example.peopleCounterAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZuHU-GxiWgJ5gsDkEkOAb7od3QhCNXzg',
    appId: '1:1075074014920:ios:80306f8250377445058ffd',
    messagingSenderId: '1075074014920',
    projectId: 'boitexinfo-analytics-fab54',
    storageBucket: 'boitexinfo-analytics-fab54.firebasestorage.app',
    iosBundleId: 'com.example.peopleCounterAnalytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt4cnbgPE92j9ilB8vmZqfbqz7DA4ucTA',
    appId: '1:1075074014920:web:1c41c90974d8a966058ffd',
    messagingSenderId: '1075074014920',
    projectId: 'boitexinfo-analytics-fab54',
    authDomain: 'boitexinfo-analytics-fab54.firebaseapp.com',
    storageBucket: 'boitexinfo-analytics-fab54.firebasestorage.app',
    measurementId: 'G-KMGG5KQ7FQ',
  );
}
